### ISSUE TITLE
一次录入多个字 Input multiple words at one time

### ISSUE THREAD

**Issue by jingcsdn** [ebitenui/ebitenui#11]
`func (t *TextInput) idleState(newKeyOrCommand bool) textInputState {
               .......
		chars := input.InputChars()
		if len(chars) > 0 {
			return t.charInputState(chars[0]), true  //多个字一起传入  return t.charInputState(chars), tru
		}
                ......  
}

func (t *TextInput) doInsert(c []rune) {
        .....
	t.cursorPosition += len(c)  //一次加多个字符位
}

func fontStringIndex(s string, f font.Face, x int) int {
	start := 0
	end := len([]rune(s))  //convert to []rune  
        line(528)  sub := string([]rune(s)[:p])  不是有可能会出现out of index 
`

**Comment by blizzy78** [comment]
I'm not sure I follow what the problem is? Please elaborate.

**Comment by jingcsdn** [comment]
sorry, it's not a bug, just add support for Chinese input

**Comment by blizzy78** [comment]
I'm afraid I'm not at all familiar with Chinese, Japanese, Arabic, and similar languages, and how to work with them in the context of string manipulation (though I'm willing to learn, of course.)
Also, I don't think Ebiten currently supports those languages. Perhaps @hajimehoshi can correct me on that.

**Comment by hajimehoshi** [comment]
Unfortunately GLFW doesn't support IMEs yet. I plan to add native transparent text fields https://github.com/hajimehoshi/ebiten/issues/1029 in the future.

**Comment by jingcsdn** [comment]
![change](https://user-images.githubusercontent.com/3411732/104685441-06457d80-5736-11eb-839c-f9cc09f5aeba.jpg)

![demo](https://user-images.githubusercontent.com/3411732/104685535-460c6500-5736-11eb-8be2-e93e58dd0a39.jpg)
[textinput.zip](https://github.com/blizzy78/ebitenui/files/5818665/textinput.zip)

**Comment by blizzy78** [comment]
Fixed, thanks!
