### ISSUE TITLE
Changing of List entries not possible after creation?

### ISSUE THREAD

**Issue by countcb** [ebitenui/ebitenui#12]
Currently is doe not seem possible to change the entries in a List after creation.

i.E. a list like this:

```
	entries := []interface{}{
		"Test 1",
		"Test 2",
		"Test 3",
	}

	list := widget.NewList(
		widget.ListOpts.Entries(entries),
		widget.ListOpts.EntryLabelFunc(func(e interface{}) string {
			return e.(string)
		}),

		[...]
		[...]
	)
```

When the slice is changed end set again for the given list only the underlying model is changed.
The widgets (buttons/labels) are not updated/removed/added.

-------

For example:

```
	entries[0] = "Changed 1"
	widget.ListOpts.Entries(entries)(list)
```

Result:
Visual change: none
Bahaviour change: **The changed list entry can no longer be selected**

-------

```
	entries = append(entries, "Teste New")
	widget.ListOpts.Entries(entries)(list)
```

Result:
Visual change: none
Bahaviour change: none

	
-------

```
	entries = []interface{}{}
	widget.ListOpts.Entries(entries)(list)

```
Result:
Visual change: none
Bahaviour change: **Clicking an entry crashes the program because of index out of bounds.**

-------

Am I missing something/doing something wrong?
Or is it not possible to change the model of a list after creation?

Currently the only way I found to update a List is by recreating the entire list, which is quite costly.
I also played around with `widget.ScrollContainerOpts.Content` to set my own container with contents that I could update. But I had no luck to get this to work at all.

Thanks for the great library!

**Comment by blizzy78** [comment]
That is correct, the List implementation needs more work being done to support changing the model on the fly. Simply changing the entries slice behind its back will result in undefined behaviour.

**Comment by countcb** [comment]
Ok, thanks for the quick reply!
That's what I expected. Just wanted to make sure I wasn't missing something obvious :)

**Comment by blizzy78** [comment]
I'm wondering, why is it costly for you to recreate the entire List?

**Comment by countcb** [comment]
The contents of my list could change each tick. I will optimize this so the list only gets updated every second though.
(the list is displaying the progress of 1-n tasks, so it is important that it is frequently updated)

Removing the List and creating a new one (every second) creates a lot of objects (Containers, Buttons, Labels).
It feels like creating a new Button just to change the buttons text. :)
That's why I thought there could be a "cheaper" way of updating the list. 

I will make more tests to find out how this approach will impact overall performance.

I hope this is understandable... if not feel free to ask more questions.

**Comment by blizzy78** [comment]
Thanks, I just wanted to get some more insight into your use case. If you can make it such that the List does not update that quickly, it shouldn't be so bad to recreate it entirely as a workaround. Of course, you will still lose the current scroll position, the selected entries, and so on.

**Comment by countcb** [comment]
I set the currently selected entry and the current scroll position the newly created list.
```
	list.SetSelectedEntry(list.SelectedEntry())
	list.SetScrollTop(list.ScrollTop())
```

To achieve this I had to add a new method to the List to get the current scroll position of the old list:

```
func (l *List) ScrollTop() float64 {
	l.init.Do()
	return float64(l.vSlider.Current) / 1000
}
```

It works quite nice. It only jumps a little bit when new entries are added.

Could something like this be added? Or is there a reason that the scroll value is not readable from the outside?
If interested I can make a PR (or if it is simpler you can add the methods) :)

**Comment by blizzy78** [comment]
No particular reason, but I can't quite remember if I was planning to enforce using methods on the vertical slider instead of using methods on the List directly. I'll look into that.

**Comment by countcb** [comment]
Recreating the entire list so often resulted in some unxecpected problems 
(list unresponsive on the frame it was recreated and 'opengl: creating framebuffer failed: 36055'.)

That's why I cobbled together some methods to Replace, Add and Remove entries in the List which work very well so far (at least for my needs).
What do you think about this? Maybe this conflicts with some of your internal plans tough.

----

Replace:
```
func (l *List) ReplaceEntry(currentEntry interface{}, newEntry interface{}) {
	l.init.Do()

	for i, b := range l.buttons {
		if l.entries[i] == currentEntry {
			l.entries[i] = newEntry
			b.Text().Label = l.entryLabelFunc(newEntry)
		}
	}
	if l.selectedEntry == currentEntry {
		l.selectedEntry = newEntry
	}
}
```

----

Add:
```
func (l *List) AddEntry(newEntry interface{}) {
	l.init.Do()

	l.entries = append(l.entries, newEntry)

	but := NewButton(
		ButtonOpts.WidgetOpts(WidgetOpts.LayoutData(RowLayoutData{
			Stretch: true,
		})),
		ButtonOpts.Image(l.entryUnselectedColor),
		ButtonOpts.TextSimpleLeft(l.entryLabelFunc(newEntry), l.entryFace, l.entryUnselectedTextColor, l.entryTextPadding),
		ButtonOpts.ClickedHandler(func(args *ButtonClickedEventArgs) {
			buttonNum := l.getButtonNum(args.Button)
			l.setSelectedEntry(l.entries[buttonNum], true)
		}))

	l.buttons = append(l.buttons, but)
	content, ok := l.scrollContainer.content.(*Container)
	if ok {
		removeChildFunc := content.AddChild(but)
		l.buttonRemoveFuncs = append(l.buttonRemoveFuncs, removeChildFunc)
	}
}
```

I'm not sure about this line
`content, ok := l.scrollContainer.content.(*Container)`
But I found no better way for now.

----

Remove:
```
func (l *List) RemoveEntry(entry interface{}) {
	l.init.Do()

	n := 0
	removedEntryNum := -1
	for _, e := range l.entries {
		if e != entry {
			l.entries[n] = e
			n++
		} else{
			l.entries[n] = nil
			removedEntryNum = n
		}
	}
	l.entries = l.entries[:n]

	if removedEntryNum != -1 {
		l.buttonRemoveFuncs[removedEntryNum]()

		n = 0
		for i,b := range l.buttons {
			if i != removedEntryNum {
				l.buttons[n] = b
				n++
			} else {
				l.buttons[n] = nil
			}
		}
		l.buttons = l.buttons[:n]

		n = 0
		for i,f := range l.buttonRemoveFuncs {
			if i != removedEntryNum {
				l.buttonRemoveFuncs[n] = f
				n++
			} else {
				l.buttonRemoveFuncs[n] = nil
			}
		}
		l.buttonRemoveFuncs = l.buttonRemoveFuncs[:n]
	}
}
```

----

Helper method:
```
func (l *List) getButtonNum(button *Button) int {
	for i, b := range l.buttons {
		if b == button {
			return i
		}
	}
	return -1
}
```

----

I had to add a new field to the List that keeps track of the funcs to remove the buttons.
`buttonRemoveFuncs []RemoveChildFunc`

List.createWidget had to be changed slightly as well.

```
func (l *List) createWidget() {
	[...]
	l.buttons = make([]*Button, 0, len(l.entries))
	l.buttonRemoveFuncs = make([]RemoveChildFunc, 0, len(l.entries))
	for _, e := range l.entries {
		e := e
		but := NewButton(
			ButtonOpts.WidgetOpts(WidgetOpts.LayoutData(RowLayoutData{
				Stretch: true,
			})),
			ButtonOpts.Image(l.entryUnselectedColor),
			ButtonOpts.TextSimpleLeft(l.entryLabelFunc(e), l.entryFace, l.entryUnselectedTextColor, l.entryTextPadding),
			ButtonOpts.ClickedHandler(func(args *ButtonClickedEventArgs) {
				buttonNum := l.getButtonNum(args.Button)
				l.setSelectedEntry(l.entries[buttonNum], true)
			}))

		l.buttons = append(l.buttons, but)
		removeChildFunc := content.AddChild(but)
		l.buttonRemoveFuncs = append(l.buttonRemoveFuncs, removeChildFunc)
	}
	[...]
}
```

The ClickHandler needs to get the number of the clicked button to get the correct entry. Otherwise the captured values in the closure would get outdated when the underlying data changes.

I could push the changes onto a new branch as well. That way it will probably be easier to see all the changes and test them out.
But I just wanted to get a first feedback this way.

**Comment by blizzy78** [comment]
Well, the current approach of the List implementation is a rather naive one, in that it simply creates all Buttons for all entries. This is not ideal, especially when you're dealing with a larger number of entries. A better approach would be to only create as many Buttons as necessary to fill the scrolling viewport area, and then reuse those Buttons to represent the correct entries as they scroll in and out of view.

I'd like to have an implementation of this ready first before starting work on supporting changes to the model on the fly. I believe the aforementioned changes would make it much easier to support model changes.

**Comment by countcb** [comment]
Understandable :)

In the meantime I pushed the changes if you want to have a look nonetheless.
https://github.com/countcb/ebitenui/commit/7931394a6a7bbaa428fe70b0672ff2aa2ce417d9
https://github.com/countcb/ebitenui/commits/listReplaceAddRemove

**Comment by mcarpenter622** [comment]
Closing due to age. Reach out if this is still a useful idea!

**Comment by countcb** [comment]
Hi,
I will have a look at the current list implementation.
Having the possibility to change the entries in a list without recreating the whole list is still a very desirable feature for me.

But I don't know yet what you changed so far.
Looking forward to check out your current version of the lib and will report back :)👍 

Edit: And thanks a lot for taking over and bringing activity back to this project. :)

**Comment by mcarpenter622** [comment]
I haven't changed much with lists yet as I haven't needed them yet for my projects, but I support the idea of editing lists. Since you responded and are still interested in this I'll reopen this ticket and see what we can do!
