### ISSUE TITLE
Large fonts can break demo button graphics

### ISSUE THREAD

**Issue by Distortions81** [ebitenui/ebitenui#15]
High font DPIs can break the nineslices.
This is the demo app, with double font DPI.

Image attached.
![Screenshot_20210704_195040](https://user-images.githubusercontent.com/33408758/124407531-5ecb0000-dd01-11eb-9afb-08c88cff57b9.png)

**Comment by blizzy78** [comment]
This is not an issue with NineSlice, but an issue with the button graphics of the demo program. The graphic in question is not designed with unlimited vertical size in mind. I'd agree that the graphic should be redesigned, but hey, I'm just a programmer 😅
