### ISSUE TITLE
when I build the demo code and run. The List looks like mosaic

### ISSUE THREAD

**Issue by sanrentai** [ebitenui/ebitenui#3]
when I build the demo code and run. The List looks like mosaic
![11](https://user-images.githubusercontent.com/26077092/98643941-b1b70800-236a-11eb-953d-b97fa29f3508.png)

**Comment by blizzy78** [comment]
I'm not sure what you mean? Please provide more information and/or a screenshot.

**Comment by sanrentai** [comment]
![11](https://user-images.githubusercontent.com/26077092/98643828-87654a80-236a-11eb-8fbe-32cdb5908926.png)

**Comment by hajimehoshi** [comment]
@sanrentai which environment / OS did you use? Thank you!

**Comment by blizzy78** [comment]
As mentioned on Gophers Slack, in the image you can also see that it is missing the solid color background. Instead it renders just black. In the demo, I've set it to not clear the background because it should always draw the background color.
Not sure if that's part of the issue.

**Comment by blizzy78** [comment]
What's also interesting is that part of the offscreen mask seems to be leaking (the purple part in the image.) I'm using `CompositeModeSourceIn` to [draw using a mask](https://github.com/blizzy78/ebitenui/blob/master/image/buffer.go#L62-L64).

**Comment by hajimehoshi** [comment]
My intuition is that PBO doesn't work well on some machines (e.g., hajimehoshi/ebiten#1208)

**Comment by blizzy78** [comment]
If pixel buffer objects are not available on an architecture, what would that mean for an Ebiten user?

**Comment by hajimehoshi** [comment]
Then Ebiten tries to send/receive pixels to/from GPU without PBO. This can be inefficient, but still works.

**Comment by sanrentai** [comment]
I use windows 10

**Comment by hajimehoshi** [comment]
Thanks! I'd like to know what kind of GPU you are using.

**Comment by sanrentai** [comment]
1. Intel(R) HD Graphics 620

2. NVIDIA GeForce 940MX

**Comment by hajimehoshi** [comment]
Did the both GPU caused this issue?

**Comment by sanrentai** [comment]
NVIDIA GeForce 940MX   OK

Intel(R) HD Graphics 620 caused this issue. It is default GPU  from Core i5-7200U
![微信图片_20201113105422](https://user-images.githubusercontent.com/26077092/99022997-a3e9c880-259e-11eb-8ec9-471cd772ee21.png)

**Comment by hajimehoshi** [comment]
@blizzy78 For the list part, is an offscreen used, or is an image is rendered on the screen directly?

**Comment by blizzy78** [comment]
The background solid color is rendered directly, while the contents is rendered into an offscreen. The offscreen contents is then composited in using `CompositeModeSourceIn`.

**Comment by hajimehoshi** [comment]
I see, thanks! The composite mode might be the key.

@sanrentai Does the Ebiten example work in your environment?

Just see https://ebiten.org/examples/masking.html no your browser

and/or

```
mkdir foo
cd foo
go mod init foo
go run -tags=example github.com/hajimehoshi/ebiten/v2/examples/masking
```

**Comment by sanrentai** [comment]
If I use Intel(R) HD Graphics 620 run the application, I saw the twinkle mosaic .
NVIDIA GeForce 940MX run the application, I saw  blur effect. I think it is correct.

**Comment by hajimehoshi** [comment]
OK, thank for confirming! So probably this is an issue in compositing mode.

Again, I appreciate your cooperation very much!

**Comment by hajimehoshi** [comment]
> If I use Intel(R) HD Graphics 620 run the application, I saw the twinkle mosaic .

Did you see the twinkle mosaic on a browser? (https://ebiten.org/examples/masking.html)

**Comment by sanrentai** [comment]
> > If I use Intel(R) HD Graphics 620 run the application, I saw the twinkle mosaic .
> 
> Did you see the twinkle mosaic on a browser? (https://ebiten.org/examples/masking.html)

No. I think it is correct.

**Comment by sanrentai** [comment]
When I use Intel UHD 630 from core i5 9300H run the  application, I think it is correct.

**Comment by hajimehoshi** [comment]
Thanks!

So this is an issue only for Intel HD Graphics 630, not UHD. Hmm...

**Comment by sanrentai** [comment]
I update the GPU driver vesion. It works well.
I think it is the bug of GPU driver

**Comment by hajimehoshi** [comment]
> I update the GPU driver vesion. It works well.

Oh, I'm glad to hear that! Then we can close this issue?

**Comment by sanrentai** [comment]
Thank you,very much!

**Comment by blizzy78** [comment]
Thanks both of you :)
