### ISSUE TITLE
Touch support

### ISSUE THREAD

**Issue by TheMightyGit** [ebitenui/ebitenui#5]
Just managed to build my game for Android (hooray!), but there doesn't appear to be any touch input support in ebintenui? 

I'm happy to take on this issue, `internal/input/input.go` looks like the right place to start?

**Comment by blizzy78** [comment]
That is correct, mobile platforms are not supported yet. I haven't looked into touch support at all yet.
And yes, that would be a good place to start.

**Comment by mcarpenter622** [comment]
With the latest release I have added a basic implementation of touch support!
